### ISSUE TITLE
Remove furnace charcoal recipes in favor of Forestry charcoal pit

### ISSUE THREAD

**Issue by Forecaster** [Forecaster/RailcraftPatronServerIssues#14]
~~Also remove Foundry coke oven charcoal recipe if it exists and is too fast (need to test)~~

**Comment by Generalcamo** [comment]
That other charcoal recipe does not exist. Not defined.

**Comment by Forecaster** [comment]
Not going to do this. Charcoal pits are too hard to use and/or bugged. I tried in single player and was unable to get one started.

**Comment by Generalcamo** [comment]
I was actually successful in making charcoal, but I did warn you that they were finicky and not user-friendly.

We can revisit this for the 1.11 series, when Charcoal Pits are not as finicky.

**Comment by Forecaster** [comment]
I was told they were poorly documented. Not that they were buggy multiblocks.

**Comment by Terpo** [comment]
For 1.11 they are fixed. Also there is a wiki page for it https://forestryforminecraft.info/other:charcoalpit

**Comment by Forecaster** [comment]
I was already aware. For 1.10 they suck however.  Which is what this issue was about.
