### ISSUE TITLE
Please consider adding reforging for ic2 tools

### ISSUE THREAD

**Issue by Ashonee75** [Forecaster/RailcraftPatronServerIssues#15]
I'm hoping we can define reforging for ic2 tools, specifically drills, chainsaws, electric wrench, treetap and hoe.

I'm going to suggest an electronic circuit as the reforging part. as it is part of the small power unit used in crafting.  it also has a reasonable cost of 1 iron, 2 copper, 2 redstone, and 6 rubber.

Thank you and have a great day!

**Comment by Generalcamo** [comment]
With very little scaling, I doubt that is too balanced.

I propose instead:
1 Iron Plate (Most Tools)
1 Bronze Plate (Electric Wrench)
1 Diamond (Diamond Drill)
1 Iridium Reinforced Plate (Iridium Drill)

**Comment by CovertJaguar** [comment]
First question....do the buffs even work?

**Comment by liach** [comment]
I think they do.

**Comment by Generalcamo** [comment]
In my testing they do. The wrench currently doesn't have any buff, but bonuses to their reach would be interesting (and also works in testing).

**Comment by liach** [comment]
@Generalcamo Can you fix this real soon? This feature has became more important to me
