### ISSUE TITLE
Track Recipe does not use railbed but uses wooden sticks instead

### ISSUE THREAD

**Issue by liach** [Forecaster/RailcraftPatronServerIssues#16]
Things are fine with electric tracks. This issue only applies to vanilla tracks. However, rails are still required.

**Comment by CovertJaguar** [comment]
Odd..

**Comment by liach** [comment]
@Forecaster This is a confirmed bug.

**Comment by Generalcamo** [comment]
I know why. It seems one of the mods adds a recipe utilizing oreDict sticks. This should be rather simple to remove, though I would like to figure out which one for future reference.

**Comment by CovertJaguar** [comment]
I'm going to guess BoP, since it adds all the sticks.
