### ISSUE TITLE
"Potion of Fire Resistance (3:00)" + Redstone makes "Potion of Heat Resistance (2:00)" instead of "Potion of Fire Resistance (8:00)"

### ISSUE THREAD

**Issue by Webcat1** [Forecaster/RailcraftPatronServerIssues#17]

**Comment by Generalcamo** [comment]
See https://github.com/Glitchfiend/ToughAsNails/issues/229

**Comment by CovertJaguar** [comment]
Seems this has been fixed in the 1.11 version, but I see no merge into 1.10.

https://github.com/Glitchfiend/ToughAsNails/pull/253

**Comment by liach** [comment]
@Forecaster I think my pull to vexatos may fix that bug.

**Comment by liach** [comment]
@Forecaster Close this please~~~
