### ISSUE TITLE
Foundry coke not convertible to RC coke.

### ISSUE THREAD

**Issue by purpleposeidon** [Forecaster/RailcraftPatronServerIssues#21]
![image](https://cloud.githubusercontent.com/assets/150333/26287339/39cfa2b8-3e2e-11e7-908f-7fd9ef20ba67.png)
![image](https://cloud.githubusercontent.com/assets/150333/26287342/42541fcc-3e2e-11e7-8948-26c839d6b6e6.png)

**Comment by CovertJaguar** [comment]
Fixed
