### ISSUE TITLE
Architect's broken. Again.

### ISSUE THREAD

**Issue by purpleposeidon** [Forecaster/RailcraftPatronServerIssues#31]

**Comment by CovertJaguar** [comment]
@purpleposeidon how?

**Comment by purpleposeidon** [comment]
I tried making various blueprints using cobblestone, and nothing was placing. I think the previous time this happened it was only working on the client? I have not tested if this is the case.

**Comment by purpleposeidon** [comment]
Yes, I have tested & it only works on the client. All regression-like.

**Comment by CovertJaguar** [comment]
hmm...

**Comment by CovertJaguar** [comment]
Ok, should be fixed next tag.
