### ISSUE TITLE
Allow joypad mod

### ISSUE THREAD

**Issue by liach** [Forecaster/RailcraftPatronServerIssues#35]
It allows users to play minecraft with a game controller.
https://github.com/ljsimin/MinecraftJoypadSplitscreenMod

**Comment by CovertJaguar** [comment]
I use this on my other game. It works well enough. I see no reason not to allow it.

**Comment by Forecaster** [comment]
Yeah this one is fine

**Comment by Forecaster** [comment]
Since we're not putting it in the pack though someone needs to provide the mod id for whitelisting

**Comment by liach** [comment]
https://github.com/ljsimin/MinecraftJoypadSplitscreenMod/blob/master/MinecraftJoypadSplitscreenMod/src/main/java/com/shiny/joypadmod/JoypadMod.java#L28

**Comment by Generalcamo** [comment]
@Forecaster Could add it as an optional mod for convenience.

**Comment by CovertJaguar** [comment]
I don't see a license anywhere, so distributing it is probably not worth the effort.
