### ISSUE TITLE
Adjust loot tables to prevent mobs dropping metals

### ISSUE THREAD

**Issue by Forecaster** [Forecaster/RailcraftPatronServerIssues#53]
Also remove zombie heat to gold nugget recipe.

This will be to further discourage mob traps to harvest iron and gold and instead encourage actual mining. In mines.

**Comment by CovertJaguar** [comment]
So....what will zombie hearts be good for then? And how will we be able to afford the gold bullets for our guns then?

**Comment by liach** [comment]
@CovertJaguar Gold is extremely cheap... On my (player's) base, we have a lot of gold. You should go to a Mesa and start mining (preferably use an advanced miner)

**Comment by Forecaster** [comment]
My gun uses lead :P
And zombie hearts have other uses

**Comment by CovertJaguar** [comment]
What other uses? You mean zombie flesh? We removed the other primary use already (charms).

**Comment by Forecaster** [comment]
Done! The hearts have two other recipes. Plus, you could you know, mine for gold :P

**Comment by liach** [comment]
mesas yeah!
