### ISSUE TITLE
Potion config is messed up

### ISSUE THREAD

**Issue by liach** [Forecaster/RailcraftPatronServerIssues#61]
The config for Not Enough potions is incorrectly named. It should use spaces instead of underscores. Moreover, @Forecaster to make combustion potion actually work you need to move it into ore brewing recipes. 

A fixed version is available [here](https://gist.github.com/liach/d15330e639f893af2641ed3bc5848fa3)

**Comment by CovertJaguar** [comment]
I just copied your lines you gave me into the original version.

**Comment by liach** [comment]
Yes, somehow the file name is wrong. See towerofawesome.org/railcraftpack/ and the files listed under the nep mod.

**Comment by liach** [comment]
Fixed :heart:
