### ISSUE TITLE
Need alternate recipes for ic2 stone dust

### ISSUE THREAD

**Issue by Ashonee75** [Forecaster/RailcraftPatronServerIssues#63]
Hoping to create recipes for stone dust + Water to make clay.

Thinking 8 dusts surrounding a water bucket to make 1 clay block, or maybe 2 clay balls

**Comment by lordebon** [comment]
Just my 2c: Dust + water seems too easy.
What about 8 dust around a sticky resin? Give a little bit of goo to hold the dust together into clay :D

**Comment by Forecaster** [comment]
Done
