### ISSUE TITLE
Request: Add recipes for advanced ejector/pulling upgrades

### ISSUE THREAD

**Issue by lordebon** [Forecaster/RailcraftPatronServerIssues#64]
These two upgrades that allow filtering do not have recipes by default - could custom ones be added?

4261/5
4261/7

**Comment by Player3324** [comment]
They do not have recipes due to their implementation being incomplete.

**Comment by lordebon** [comment]
Thanks player - I thought I'd seen them complete but must have mixed them up with something else.
