### ISSUE TITLE
AR pipes continue to crash the server

### ISSUE THREAD

**Issue by purpleposeidon** [Forecaster/RailcraftPatronServerIssues#65]

**Comment by Forecaster** [comment]
An official update has been applied as of today, we'll see what happens

**Comment by purpleposeidon** [comment]
Just crashed. Got a log?
Here's what's just happened:
1. Observe the pipes aren't working, again.
2. Flip them all off.
3. Flip them back on one by one
4. Crash!

**Comment by Forecaster** [comment]
This: https://gist.github.com/Forecaster/9f23e9d0b2d4bd2904341d98b7b02c4b

ConcurrentModificationException

**Comment by purpleposeidon** [comment]
![ar-diagram](https://user-images.githubusercontent.com/150333/28503308-f8ef561e-6fb8-11e7-94cf-623f84a817ff.png)

**Comment by Generalcamo** [comment]
Updated... -again- to hopefully fix server crashes.

**Comment by Forecaster** [comment]
Pressure Pipes has been added to allow avoiding using AR pipes.
