### ISSUE TITLE
Iron Scaffolds act as fuel?

### ISSUE THREAD

**Issue by Ashonee75** [Forecaster/RailcraftPatronServerIssues#71]
I found out iron scaffolds act as fuel when my tunnel bore started to burn them.

Recipe is 7.5 iron ingot equivalents.  No other material.

I'm thinking it shouldn't be a valid fuel.

**Comment by Forecaster** [comment]
This seems to be an ic2 issue. Presumably the iron scaffolds are treated as fuel because they share the block id `ic2:scaffold` with the wooden ones.
Though if people want to burn iron I don't see a big issue with that. Wood is far easier to get.

**Comment by Forecaster** [comment]
Confirmed in instance with just ic2 by the way.

**Comment by Player3324** [comment]
Not reasonably fixable, broken vanilla burn handler takes precedence.

**Comment by Forecaster** [comment]
Since this is non-critical and unfixable at the moment I'm going to close this.
