### ISSUE TITLE
Portion of Heat Resistance crashing client

### ISSUE THREAD

**Issue by Oeniarku** [Forecaster/RailcraftPatronServerIssues#73]
In order to crash one must be under hyperthermia.

**Comment by Oeniarku** [comment]
Hah. Found a bunch of issues about this problem. Oldest on 4 July 2016. Is it so rare? The Nether is annoying like hell, with this bug.

Sorry for my English.

**Comment by liach** [comment]
You can find some cold biome and get some freeze rods first to make some coolers. That might prevent crashing.

**Comment by Forecaster** [comment]
Temperature mechanic disabled until further notice, rendering this issue irrelevant.
