### ISSUE TITLE
Cocobolo Wood

### ISSUE THREAD

**Issue by NightwolfBlue** [Forecaster/RailcraftPatronServerIssues#87]
Cocobolo Wood from Forestry can not be cut in the Block cutting machine.

**Comment by NightwolfBlue** [comment]
I did some checking.
forestry:logs.0 and forestry:logs.1 and there fireproof version can be cut, but forestry:logs.2-7 can not. Also Natura Redwood and Bloodwood.

I hope this helps.

**Comment by Generalcamo** [comment]
Duplicate of #13
