### ISSUE TITLE
Pam's Garden

### ISSUE THREAD

**Issue by NightwolfBlue** [Forecaster/RailcraftPatronServerIssues#91]
The garden are not dropping items.

**Comment by NightwolfBlue** [comment]
The garden that you find in world should drop random Pam's Crops.
http://harvestcraftmod.wikia.com/wiki/Garden

**Comment by Forecaster** [comment]
Obviously this broke in this update

`Pam's Harvest Craft 1.9.4h => 1.9.4j`

We could roll back to the previous version.

**Comment by Generalcamo** [comment]
I can't confirm, I'm breaking Air Gardens and getting items from them.

**Comment by Forecaster** [comment]
I've noticed desert/arid gardens (the small cacti with the red thing on them) don't drop fruits anymore. So it's confirmed that at least some gardens have no drops anymore.

**Comment by NightwolfBlue** [comment]
I believe it was gourd and ground that didn't work for me

**Comment by Generalcamo** [comment]
Fixed in next update
